// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutoOneBall.h"
#include "Commands/CatapultForwardSlow.h"
#include "Commands/CatapultOff.h"
#include "Commands/CatapultReverseSlow.h"
#include "Commands/ChassisTankDrive.h"
#include "Commands/IntakeOff.h"
#include "Commands/IntakeOn.h"
#include "Commands/PressurizerCompress.h"
#include "Commands/ShifterShift.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() {
	// Process operator interface input here.
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	coDriver = new Joystick(2);
	
	cRBumper = new JoystickButton(coDriver, 6);
	cRBumper->WhenReleased(new CatapultForwardSlow());
	driver = new Joystick(1);
	
	dLeftStick = new JoystickButton(driver, 9);
	dLeftStick->WhenReleased(new ShifterShift());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("AutoOneBall", new AutoOneBall());
	SmartDashboard::PutData("ChassisTankDrive", new ChassisTankDrive());
	SmartDashboard::PutData("IntakeOff", new IntakeOff());
	SmartDashboard::PutData("IntakeOn", new IntakeOn());
	SmartDashboard::PutData("PressurizerCompress", new PressurizerCompress());
	SmartDashboard::PutData("ShifterShift", new ShifterShift());
	SmartDashboard::PutData("CatapultOff", new CatapultOff());
	SmartDashboard::PutData("CatapultForwardSlow", new CatapultForwardSlow());
	SmartDashboard::PutData("CatapultReverseSlow", new CatapultReverseSlow());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getCoDriver() {
	return coDriver;
}
Joystick* OI::getDriver() {
	return driver;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
