// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.



#include "CatapultShootSuper.h"
#include "IntakeToggle.h"
#include "HuggerToggle.h"
#include "DelayBeforeShoot.h"
#include "CatapultShootAfterDelay.h"


CatapultShootSuper::CatapultShootSuper() {
	
	AddSequential(new IntakeToggle());
	AddSequential(new HuggerToggle());
	AddSequential(new DelayBeforeShoot());
	AddSequential(new CatapultShootAfterDelay());
}
