// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#include "IntakeOn.h"
IntakeOn::IntakeOn():intakeSwitch(true)
{
	
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::intake);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::catapult);
}
// Called just before this Command runs the first time
void IntakeOn::Initialize() {
	
}
// Called repeatedly when `this Command is scheduled to run
void IntakeOn::Execute() {
	if (intakeSwitch)
	{
		Robot::intake->talon9->Set(1.0);
		Robot::intake->lights->Set(Relay::kForward);
		Robot::catapult->catapultDoubleSolenoid->Set(DoubleSolenoid::kForward);
		intakeSwitch = false;
	}
	else
	{
		Robot::intake->lights->Set(Relay::kReverse);
		Robot::catapult->catapultDoubleSolenoid->Set(DoubleSolenoid::kReverse);
		Robot::intake->talon9->Set(0.0);
		intakeSwitch = true;
	}
}
// Make this return true when this Command no longer needs to run execute()
bool IntakeOn::IsFinished() {	
	return true;
}
// Called once after isFinished returns true
void IntakeOn::End() {
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void IntakeOn::Interrupted() {
}
