// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "Chassis.h"
#include "../Robotmap.h"
#include "../Commands/ChassisTankDrive.h"
Chassis::Chassis() : Subsystem("Chassis"),
mReversed(false)
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	talon1 = RobotMap::chassisTalon1;
	talon2 = RobotMap::chassisTalon2;
	talon3 = RobotMap::chassisTalon3;
	talon4 = RobotMap::chassisTalon4;
	talon5 = RobotMap::chassisTalon5;
	talon6 = RobotMap::chassisTalon6;
	encoder1 = RobotMap::chassisEncoder1;
	encoder2 = RobotMap::chassisEncoder2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	robotDrive = RobotMap::chassisRobotDrive;
}
    
void Chassis::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	SetDefaultCommand(new ChassisTankDrive());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
